version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env
    ports:
      - 4000:4000
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    volumes:
      - redis-data:/data
volumes:
  db-data: {}
  redis-data: {}
